workflows:
  android-workflow:
    name: TvFlix Host - Android Build
    max_build_duration: 60
    instance_type: linux_x2
    working_directory: tvflix-host
    environment:
      vars:
        PACKAGE_NAME: "com.djamylova.tvflixhost"
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/tvflix-host/local.properties"
      - name: Build debug APK
        script: |
          cd $CM_BUILD_DIR/tvflix-host
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - tvflix-host/app/build/outputs/**/*.apk
